### ISSUE TITLE
Forge Setup is Confusing (Docker Username)

### ISSUE THREAD

**Issue by plombardi89** [datawire/forge#10]
Not sure why Forge believes it's a good idea to default to my computer's login name as the username for forge. That's not likely to be a sensible default at all given that there are a whole heck of a lot of `plombardi`  users in the world. My actual username for Docker Hub is `plombardi89`.

Also it's not clear how Forge would work with a Container Registry that uses non traditional Username/Password login such as Google Container Registry or ECR.

**Comment by rhs** [comment]
This is fixed now.
