### ISSUE TITLE
Putting Docker Login password (base64 encoded) into forge.yaml is NO BUENO

### ISSUE THREAD

**Issue by plombardi89** [datawire/forge#11]
I just committed my Docker Hub password to source control (in `forge.yaml`). Thankfully it's not a public repository and I can delete the source tree but that's really really bad.

**Comment by rhs** [comment]
This file shouldn't ever need to be committed to github. It only contains global configuration (all service specific configuration is in service.yaml). I've added a big warning into the generated file that it contains secrets and that it should not be checked into github.
