### ISSUE TITLE
Need error message when USER env variable not set

### ISSUE THREAD

**Issue by richarddli** [datawire/forge#18]
This is what you get when you run forge setup inside a Docker container

`

> forge setup
--
  | == Checking Kubernetes Setup ==
  |  
  | CMD: kubectl version --short -> Client Version: v1.6.0
  | Server Version: v1.6.0
  | CMD: kubectl get service kubernetes --namespace default -> NAME         CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
  | kubernetes   10.96.0.1    <none>        443/TCP   10m
  | Traceback (most recent call last):
  | File "/home/scrapbook/.bin/forge/bin/forge", line 11, in <module>
  | load_entry_point('Forge==0.2.6+1.g161789d', 'console_scripts', 'forge')()
  | File "/home/scrapbook/.bin/forge/venv/local/lib/python2.7/site-packages/forge/cli.py", line 388, in call_main
  | exit(main())
  | File "/home/scrapbook/.bin/forge/venv/local/lib/python2.7/site-packages/forge/cli.py", line 350, in main
  | if args["setup"]: return forge.setup()
  | File "/home/scrapbook/.bin/forge/venv/local/lib/python2.7/site-packages/forge/cli.py", line 124, in setup
  | user = os.environ["USER"]
  | File "/home/scrapbook/.bin/forge/venv/lib/python2.7/UserDict.py", line 23, in __getitem__
  | raise KeyError(key)
  | KeyError: 'USER'

`

**Comment by ark3** [comment]
FYI popular Docker images (Alpine, Ubuntu) don't set `$USER` by default. We should manually run a Forge smoke test inside Docker to see whether we run into other such issues.

**Comment by plombardi89** [comment]
Environment variables are just notoriously flaky in general. It's often hard to figure out what's required by (insert spec here... POSIX?) vs. what various shells include. Since Alpine and Ubuntu don't use Bash this could be a case where USER is Bashism. I've often made the mistake of using Bash only environment variables.

Further complicating matters is Windows compatibility if we ever go down that route.

**Comment by rhs** [comment]
I did a quick fix for this and made sure we have no other hard dependencies on any environment variables. I will open a separate issue for adding some smoke tests inside docker.
