### ISSUE TITLE
Sub directory not deployed

### ISSUE THREAD

**Issue by pkim-auro** [datawire/forge#192]
HI,

When my directory looks like this:
../k8s/deployment.yaml - it works

with: 
../k8s/forge-template/deployment.yaml - it renders but it fails to deploy.

here's the text from **forge deploy**
║ rendered: (none)
║ deployed: portfolio-service

I can code in a workaround I think but I'm hoping this is a simple fix.

**Comment by pkim-auro** [comment]
i was able to make it wake up like this: 
with:
../k8s/deloyment.yaml -> only container an initial line of "---"
../k8s/forge-template/deployment.yaml - it renders but it fails to deploy.

**Comment by rhs** [comment]
This should be fixed now in 0.4.12
