### ISSUE TITLE
Ability to control build parallelism

### ISSUE THREAD

**Issue by arvola** [datawire/forge#208]
It would be very useful to have a way to control how much Forge parallelizes builds. At minimum viable, Forge should allow turning parallelization off.

Background:
Running builds in parallel can lead to the following Docker bug: https://github.com/moby/moby/issues/9656 - depending on the number of builds and if they share file system layers. It can make builds take an order of magnitude longer. In my case, a 5 minute build could take up to 2 hours.

**Comment by rhs** [comment]
This should be fixed in 0.4.14. You can set the concurrency parameter in forge.yaml (it now defaults to 5 so you may not need to set it).
