### ISSUE TITLE
create a spec for service.yaml

### ISSUE THREAD

**Issue by rhs** [datawire/forge#22]

**Comment by tristanpemble** [comment]
This would be helpful for future proofing `service.yaml`; I feel weird putting my service-specific configuration at the top level since it may collide with configuration keys added to Forge in the future. A formal spec would help

**Comment by rhs** [comment]
I've added a schema and you can read the docs here: https://forge.sh/reference/service-descriptor

I'm open to any ideas on avoiding collision, e.g. we could define a reserved map or something:

service.yaml:
  name: ...
  config: # guaranteed to never be used by forge
    foo: bar

**Comment by rhs** [comment]
I've added config to the schema as a reserved object.
