### ISSUE TITLE
Forge build is painful to work with using a compiled language.

### ISSUE THREAD

**Issue by plombardi89** [datawire/forge#31]
The `forge build` command which converts source to Docker images is painfully slow for projects that need to pull dependencies and compile from source for changes. There is no easy or good way to cache the dependencies or do an incremental build which means that the speed benefit of Forge is lost immediately for these types of languages.

The Docker build itself took `46.36` seconds for a very simple "Hello, world!" type application.
Forge itself took `57.16` seconds.

If I wasn't running the build of source code in a Dockerfile and could reuse my local build caches then my build time drops massively. Here is a Gradle run:

```
plombardi@palwork ~/w/kubernaut-monorepo> ./gradlew clean test shadowJar

> Task :common:compileKotlin
Using kotlin incremental compilation

> Task :poolman:compileKotlin
Using kotlin incremental compilation

> Task :web:compileKotlin
Using kotlin incremental compilation


BUILD SUCCESSFUL in 3s
13 actionable tasks: 13 executed
```

**Comment by rhs** [comment]
The rebuilder support added in 0.3.3 addresses this.
