### ISSUE TITLE
Enhance CLI documentation of commands

### ISSUE THREAD

**Issue by tristanpemble** [datawire/forge#36]
`forge --help` doesn't give much information about what `bake`, `push`, etc do. Would help to have more detailed documentation on the commands and their arguments.

**Comment by plombardi89** [comment]
@rhs I took a look to see if we could do anything here and until we switch out the CLI framework (docopt) for something different (potentially click 6.x) we're not going to be able to document the actual arguments. Docopt is limited to descriptions for options only.

**Comment by rhs** [comment]
The latest forge (0.3) has moved over to click and includes significantly more command line docs.
