### ISSUE TITLE
Branch Awareness

### ISSUE THREAD

**Issue by plombardi89** [datawire/forge#37]
It would be nice to have VCS (Git) Branch Awareness built into Forge so that for example if several development feature branches are open for a service they can all be deployed at once.

I have been doing a lot of thinking around the use of namespaces recently. It seems ideally the proper use of a namespace is to make them at a minimum application centric so that it's not possible for different applications or teams to conflict on a common name inside of a namespace (e.g. consider what happens if two teams or applications want to have something named `api`).

So that leaves us with at a minimum most folks should use something like below:

```yaml
namespace: "${APP_NAME}"  # "kubernaut"
```

If you're like us and want to run multiple operational environments out of the same cluster then you also likely need to append an environment name to the namespace, for example, we use a single cluster for `prod` and `staging`.

```yaml
namespace: "${APP_NAME}-${APP_ENV}"  # "kubernaut-prod" or "kubernaut-rc"
```

Now consider you have a situation where two or three developers hack on a single Application composed of <N> microservices all under the same repository. They use branch names like `dev/cool-new-feature1`. It would be nice if Forge could have a way to just generate the proper namespace to deploy into. Some tools do something like `${APP_NAME}-${Eight_Character_String} to ensure uniqueness but other ideas would be to do `${APP_NAME}-${BRANCH_NAME}`

**Comment by rhs** [comment]
Profile support in 0.3.9 addresses branch awareness. I believe the patterns described here could be setup based on that.
