### ISSUE TITLE
Create a ${PROJECT_ROOT}/.forge directory rather than ${PROJECT_ROO}/work

### ISSUE THREAD

**Issue by plombardi89** [datawire/forge#40]
Many other tools follow the convention of using dot-file directories for storing local project configuration, caches and outputs. Forge should do the same thing. The directory "work" is pretty common and likely to be used already for something by a project.

Other tools:
- git (`.git`)
- Gradle (`.gradle`)
- Intellij (`.idea`)

I can probably think of others, but the convention stands.

**Comment by rhs** [comment]
This was fixed a while ago.
