### ISSUE TITLE
Forge should respect .gitignore when computing hash

### ISSUE THREAD

**Issue by plombardi89** [datawire/forge#44]
Forge currently just uses the entire source tree but it really should respect the gitignore otherwise the hash will never be the same as the actual git hash for the source tree.

Not sure if there is a python implementation of the gitignore rules, but another option is to use the `git` command itself which offers powerful capabilities for inspecting ignored files: 

https://stackoverflow.com/questions/466764/git-command-to-show-which-specific-files-are-ignored-by-gitignore

**Comment by rhs** [comment]
This is fixed in 0.3.1
