### ISSUE TITLE
MacOS : documentation should mention that virtualenv is needed

### ISSUE THREAD

**Issue by fmedery** [datawire/forge#5]
Hello,
Just started with forge quickstart page but  script return:
```--> Performing installation environment sanity checks...
-->  Checking for python: OK
-->  Checking for virtualenv: FAIL

        Cannot find virtualenv, please install and try again.
```

Documentation should mention that virtualenv is needed

```
pip install virtualenv
```
did the trick:
```
--> Performing installation environment sanity checks...
-->  Checking for python: OK
-->  Checking for virtualenv: OK
-->  Checking install target: OK
--> Creating /Users/fmedery/forge installation directory...
--> Installing Forge...
--> Installed!

  Forge has been installed into '/Users/fmedery/forge'. You may want to
  add '/Users/fmedery/forge/bin' to your PATH.
```

**Comment by danielbryantuk** [comment]
I bumped into a similar issue @fmedery, where forge reported that virtualenv was installed, but it wasn't showing on 'pip list' (or I believe it was an old version I somehow installed).

As suggested by @rhs, running 'pip install -U virtualenv' solved the issue for me, and I also had to update 'setuptools' as well -> 'pip install -U setuptools'

**Comment by richarddli** [comment]
Thanks, fixed!
