### ISSUE TITLE
Forge Setup is Confusing (Docker Repo)

### ISSUE THREAD

**Issue by plombardi89** [datawire/forge#9]
The command `forge setup` is confusing. Every Docker Registry implementation in existence uses the following format for a repository name: `$namespace/$image_name`. When running `forge setup` you're prompted for `Docker repo:` and the inclination is to put in something like `plombardi89/helloworld`, however, if you do that then the `forge setup` fails later on:

```
Command[ERR[1]]: docker push registry.hub.docker.com/plombardi89/bookinfo/forge_test:dummy
  The push refers to a repository [registry.hub.docker.com/plombardi89/bookinfo/forge_test]
  3fb66f713c9f: Preparing
  error parsing HTTP 404 response body: invalid character '<' looking for beginning of value: "<!doctype html>\n<html class=\"no-js\" lang=\"\">\n    <head>\n        <meta
```
The problem is Forge is expecting just the `$namespace` part of the image name (e.g. `plombardi89`) and not the the `$image_name` bit which it will create for the project based on the current working directories name.

**Comment by rhs** [comment]
This should be fixed now. Let me know if it is still confusing.
